owner: hkfires
repo: WebStatusMonitor

sites:
  - name: Serv00-1
    url: $URL_SERV00_1
  - name: Serv00-2
    url: $URL_SERV00_2
  - name: Serv00-3
    url: $URL_SERV00_3
  - name: Serv00-4
    url: $URL_SERV00_4
  - name: Serv00-5
    url: $URL_SERV00_5
  - name: Bot-Serv00
    url: $URL_BOT_SERV00
  - name: Bot-CT8
    url: $URL_BOT_CT8
  - name: Bot-Home
    url: $URL_BOT_HOME
  - name: Google
    url: https://www.google.com
  - name: Baidu
    url: https://www.baidu.com/
  - name: Cloudflare
    url: https://www.cloudflare.com/

status-website:
  theme: ocean
  cname: webstatus.us.kg
  # baseUrl: /WebStatusMonitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Web Status Monitor
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
